#开发环境配置

server:
  tomcat:
    uri-encoding: UTF-8
  port: 5000
  servlet:
    session:
      timeout: 0


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: xjh19951029SHNU!
    url: jdbc:mysql://47.103.15.229:3306/missyou?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    username: root


# 开启权限拦截
auth:
  enabled: true


# 开启http请求日志记录
request-log:
  enabled: true


logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录
    io.github.talelin.latticy.mapper: debug




